import type { FastifyPluginAsync,FastifyRequest } from 'fastify';
import { addMemberRequestSchema,conversationParamsSchema,createConversationRequestSchema,editMessageRequestSchema,listMessagesQuerySchema,memberParamsSchema,messageParamsSchema,sendMessageRequestSchema,updateConversationRequestSchema,updateMemberRoleRequestSchema } from '@vibeline/contracts';
import { validate } from '@/utils/validation';
import { realtimePublisher } from './realtime.publisher';
import { chatService } from './chat.service';

const userId=(request:FastifyRequest)=>request.user.sub;
export const chatRoutes:FastifyPluginAsync=async(app)=>{
  app.addHook('preHandler',app.authenticate);
  app.post('/conversations',async(request,reply)=>{const body=validate(createConversationRequestSchema,request.body);const conversation=await chatService.createConversation(userId(request),body.participantUserIds,body.type,body.title);return reply.status(201).send({conversation});});
  app.get('/conversations',async request=>({conversations:await chatService.listConversations(userId(request))}));
  app.get('/conversations/:conversationId',async request=>{const {conversationId}=validate(conversationParamsSchema,request.params);return chatService.getConversation(userId(request),conversationId);});
  app.patch('/conversations/:conversationId',async request=>{const {conversationId}=validate(conversationParamsSchema,request.params);const body=validate(updateConversationRequestSchema,request.body);return {conversation:await chatService.updateConversation(userId(request),conversationId,body.title)};});
  app.post('/conversations/:conversationId/members',async request=>{const {conversationId}=validate(conversationParamsSchema,request.params);const body=validate(addMemberRequestSchema,request.body);return chatService.addMember(userId(request),conversationId,body.userId);});
  app.patch('/conversations/:conversationId/members/:userId',async request=>{const params=validate(memberParamsSchema,request.params);const body=validate(updateMemberRoleRequestSchema,request.body);return {member:await chatService.updateMemberRole(userId(request),params.conversationId,params.userId,body.role)};});
  app.delete('/conversations/:conversationId/members/:userId',async(request,reply)=>{const params=validate(memberParamsSchema,request.params);await chatService.removeMember(userId(request),params.conversationId,params.userId);return reply.status(204).send();});
  app.post('/conversations/:conversationId/leave',async(request,reply)=>{const {conversationId}=validate(conversationParamsSchema,request.params);await chatService.leaveConversation(userId(request),conversationId);return reply.status(204).send();});
  app.get('/conversations/:conversationId/messages',async request=>{const {conversationId}=validate(conversationParamsSchema,request.params);const query=validate(listMessagesQuerySchema,request.query);const messages=await chatService.listMessages(userId(request),conversationId,query.beforeSequence,query.afterSequence,query.limit);return {messages,nextCursor:query.afterSequence===undefined&&messages.length===query.limit?messages[0]?.sequence:undefined};});
  app.post('/conversations/:conversationId/messages',async(request,reply)=>{const {conversationId}=validate(conversationParamsSchema,request.params);const body=validate(sendMessageRequestSchema,request.body);const result=await chatService.sendMessage(userId(request),conversationId,body.clientMessageId,body.body);return reply.status(result.created?201:200).send({message:result.message,duplicate:!result.created});});
  app.patch('/conversations/:conversationId/messages/:messageId',async request=>{const params=validate(messageParamsSchema,request.params);const body=validate(editMessageRequestSchema,request.body);return {message:await chatService.editMessage(userId(request),params.conversationId,params.messageId,body.body)};});
  app.delete('/conversations/:conversationId/messages/:messageId',async request=>{const params=validate(messageParamsSchema,request.params);return {message:await chatService.deleteMessage(userId(request),params.conversationId,params.messageId)};});
  app.get('/events',async(request,reply)=>{reply.hijack();const response=reply.raw;response.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});response.write('event: connected\ndata: {}\n\n');const unsubscribe=realtimePublisher.subscribe(userId(request),event=>response.write(`event: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`));const heartbeat=setInterval(()=>response.write(': heartbeat\n\n'),25_000);const maxLifetime=setTimeout(()=>response.end(),10*60_000);request.raw.on('close',()=>{clearInterval(heartbeat);clearTimeout(maxLifetime);unsubscribe();});});
};
