import { randomUUID } from 'node:crypto';
import { and, asc, desc, eq, gt, inArray, isNull, lt, sql } from 'drizzle-orm';
import { db } from '@/db/client';
import { conversationMemberReceipts, conversationMembers, conversations, messages, messageAttachments, mediaAssets, messageReactions, messageUserDeletions, userPresence, users } from '@/db/schema';

const activeMembership = (conversationId:string,userId:string) => and(eq(conversationMembers.conversationId,conversationId),eq(conversationMembers.userId,userId),isNull(conversationMembers.leftAt));

class ChatRepository {
  async usersExist(userIds:string[]){if(!userIds.length)return true;const rows=await db.select({id:users.id}).from(users).where(inArray(users.id,userIds));return rows.length===new Set(userIds).size;}
  async createConversation(creatorId:string,participantUserIds:string[],type:'direct'|'group',title?:string){
    const memberIds=[...new Set([creatorId,...participantUserIds])]; const directKey=type==='direct'?[...memberIds].sort().join(':'):null;
    return db.transaction(async tx=>{
      if(directKey){const existing=await tx.query.conversations.findFirst({where:eq(conversations.directKey,directKey)});if(existing)return existing;}
      const insert=tx.insert(conversations).values({id:randomUUID(),type,directKey,title:type==='group'?title:null});
      const [created]=directKey?await insert.onConflictDoNothing({target:conversations.directKey}).returning():await insert.returning();
      if(!created&&directKey){const existing=await tx.query.conversations.findFirst({where:eq(conversations.directKey,directKey)});if(existing)return existing;throw new Error('Direct conversation conflict did not resolve');}
      const conversation=created!;
      await tx.insert(conversationMembers).values(memberIds.map(userId=>({id:randomUUID(),conversationId:conversation.id,userId,role:type==='group'&&userId===creatorId?'owner' as const:'member' as const,joinedSequence:1})));
      return conversation;
    });
  }
  getConversation(id:string){return db.query.conversations.findFirst({where:eq(conversations.id,id)});}
  getMessage(id:string,messageId:string){return db.query.messages.findFirst({where:and(eq(messages.id,messageId),eq(messages.conversationId,id))});}
  getMembership(id:string,userId:string){return db.query.conversationMembers.findFirst({where:activeMembership(id,userId)});}
  async getQuickEmoji(id:string,userId:string){const row=await this.getMembership(id,userId);return row?.quickEmoji;}
  async setQuickEmoji(id:string,userId:string,emoji:string){const [row]=await db.update(conversationMembers).set({quickEmoji:emoji}).where(activeMembership(id,userId)).returning({quickEmoji:conversationMembers.quickEmoji});return row;}
  async listReactions(id:string,userId:string){if(!(await this.getMembership(id,userId)))return null;return db.select({messageId:messageReactions.messageId,userId:messageReactions.userId,emoji:messageReactions.emoji,createdAt:messageReactions.createdAt}).from(messageReactions).innerJoin(messages,eq(messages.id,messageReactions.messageId)).where(and(eq(messages.conversationId,id),isNull(messages.deletedAt))).orderBy(asc(messageReactions.createdAt));}
  async addReaction(id:string,userId:string,messageId:string,emoji:string){if(!(await this.getMembership(id,userId)))return {kind:'not-found' as const};const message=await this.getMessage(id,messageId);if(!message||message.deletedAt)return {kind:'message-not-found' as const};const [row]=await db.insert(messageReactions).values({id:randomUUID(),messageId,userId,emoji}).onConflictDoNothing({target:[messageReactions.messageId,messageReactions.userId,messageReactions.emoji]}).returning();return {kind:'ok' as const,reaction:row};}
  async removeReaction(id:string,userId:string,messageId:string,emoji:string){if(!(await this.getMembership(id,userId)))return {kind:'not-found' as const};const message=await this.getMessage(id,messageId);if(!message)return {kind:'message-not-found' as const};await db.delete(messageReactions).where(and(eq(messageReactions.messageId,messageId),eq(messageReactions.userId,userId),eq(messageReactions.emoji,emoji)));return {kind:'ok' as const};}
  listMembers(id:string){return db.select({userId:users.id,displayName:users.displayName,avatarUrl:users.avatarUrl,role:conversationMembers.role,joinedAt:conversationMembers.joinedAt,joinedSequence:conversationMembers.joinedSequence,deliveredSequence:sql<number>`COALESCE(${conversationMemberReceipts.deliveredSequence},0)`,readSequence:sql<number>`COALESCE(${conversationMemberReceipts.readSequence},0)`,lastSeenAt:userPresence.lastSeenAt}).from(conversationMembers).innerJoin(users,eq(users.id,conversationMembers.userId)).leftJoin(conversationMemberReceipts,and(eq(conversationMemberReceipts.conversationId,id),eq(conversationMemberReceipts.userId,users.id))).leftJoin(userPresence,eq(userPresence.userId,users.id)).where(and(eq(conversationMembers.conversationId,id),isNull(conversationMembers.leftAt)));}
  listMessageRecipientIds(id:string,sequence:number){return db.select({userId:conversationMembers.userId}).from(conversationMembers).where(and(eq(conversationMembers.conversationId,id),isNull(conversationMembers.leftAt),sql`${conversationMembers.joinedSequence} <= ${sequence}`));}
  listConversations(userId:string){return db.select({
    id:conversations.id,type:conversations.type,title:conversations.title,createdAt:conversations.createdAt,updatedAt:conversations.updatedAt,archivedAt:conversations.archivedAt,
    displayTitle:sql<string>`CASE WHEN ${conversations.type} = 'direct' THEN COALESCE((SELECT u.display_name FROM conversation_members cm JOIN users u ON u.id = cm.user_id WHERE cm.conversation_id = ${conversations.id} AND cm.user_id <> ${userId} AND cm.left_at IS NULL LIMIT 1),'Conversation') ELSE COALESCE(${conversations.title},'Group conversation') END`,
    avatarUrl:sql<string|null>`CASE WHEN ${conversations.type} = 'direct' THEN (SELECT u.avatar_url FROM conversation_members cm JOIN users u ON u.id = cm.user_id WHERE cm.conversation_id = ${conversations.id} AND cm.user_id <> ${userId} AND cm.left_at IS NULL LIMIT 1) ELSE NULL END`,
    lastMessage:sql<string|null>`(SELECT m.body FROM messages m WHERE m.conversation_id = ${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} AND NOT EXISTS (SELECT 1 FROM message_user_deletions mud WHERE mud.message_id=m.id AND mud.user_id=${userId}) ORDER BY m.sequence DESC LIMIT 1)`,
    lastMessageAt:sql<Date|null>`(SELECT m.created_at FROM messages m WHERE m.conversation_id = ${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} AND NOT EXISTS (SELECT 1 FROM message_user_deletions mud WHERE mud.message_id=m.id AND mud.user_id=${userId}) ORDER BY m.sequence DESC LIMIT 1)`,
    lastMessageSenderId:sql<string|null>`(SELECT m.sender_id FROM messages m WHERE m.conversation_id = ${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} AND NOT EXISTS (SELECT 1 FROM message_user_deletions mud WHERE mud.message_id=m.id AND mud.user_id=${userId}) ORDER BY m.sequence DESC LIMIT 1)`,
    lastMessageSequence:sql<number|null>`(SELECT m.sequence FROM messages m WHERE m.conversation_id = ${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} AND NOT EXISTS (SELECT 1 FROM message_user_deletions mud WHERE mud.message_id=m.id AND mud.user_id=${userId}) ORDER BY m.sequence DESC LIMIT 1)`,
    lastMessageAttachmentCount:sql<number>`COALESCE((SELECT COUNT(*)::int FROM message_attachments ma WHERE ma.message_id = (SELECT m.id FROM messages m WHERE m.conversation_id = ${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} AND NOT EXISTS (SELECT 1 FROM message_user_deletions mud WHERE mud.message_id=m.id AND mud.user_id=${userId}) ORDER BY m.sequence DESC LIMIT 1)),0)`,
    lastMessageHasAudio:sql<boolean>`COALESCE((SELECT BOOL_OR(a.mime_type LIKE 'audio/%' OR (a.mime_type NOT LIKE 'video/%' AND COALESCE(a.original_filename,'') ~* '\\.(webm|ogg|oga|opus|m4a)$')) FROM message_attachments ma JOIN media_assets a ON a.id=ma.media_asset_id WHERE ma.message_id = (SELECT m.id FROM messages m WHERE m.conversation_id = ${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} AND NOT EXISTS (SELECT 1 FROM message_user_deletions mud WHERE mud.message_id=m.id AND mud.user_id=${userId}) ORDER BY m.sequence DESC LIMIT 1)),false)`,
    lastMessageHasVideo:sql<boolean>`COALESCE((SELECT BOOL_OR(a.mime_type LIKE 'video/%' OR COALESCE(a.original_filename,'') ~* '\\.(mp4|mov|m4v)$') FROM message_attachments ma JOIN media_assets a ON a.id=ma.media_asset_id WHERE ma.message_id = (SELECT m.id FROM messages m WHERE m.conversation_id = ${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} AND NOT EXISTS (SELECT 1 FROM message_user_deletions mud WHERE mud.message_id=m.id AND mud.user_id=${userId}) ORDER BY m.sequence DESC LIMIT 1)),false)`,
    lastMessageDeletedAt:sql<Date|null>`(SELECT m.deleted_at FROM messages m WHERE m.conversation_id = ${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} AND NOT EXISTS (SELECT 1 FROM message_user_deletions mud WHERE mud.message_id=m.id AND mud.user_id=${userId}) ORDER BY m.sequence DESC LIMIT 1)`,
    unreadCount:sql<number>`(SELECT COUNT(*)::int FROM messages m WHERE m.conversation_id=${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} AND m.sequence > COALESCE((SELECT cmr.read_sequence FROM conversation_member_receipts cmr WHERE cmr.conversation_id=${conversations.id} AND cmr.user_id=${userId}),0) AND (m.sender_id IS NULL OR m.sender_id <> ${userId}) AND NOT EXISTS (SELECT 1 FROM message_user_deletions mud WHERE mud.message_id=m.id AND mud.user_id=${userId}))`,
    peerLastSeenAt:sql<Date|null>`CASE WHEN ${conversations.type}='direct' THEN (SELECT up.last_seen_at FROM conversation_members cm LEFT JOIN user_presence up ON up.user_id=cm.user_id WHERE cm.conversation_id=${conversations.id} AND cm.user_id<>${userId} AND cm.left_at IS NULL LIMIT 1) ELSE NULL END`,
    peerDeliveredSequence:sql<number>`CASE WHEN ${conversations.type}='direct' THEN COALESCE((SELECT cmr.delivered_sequence FROM conversation_members cm LEFT JOIN conversation_member_receipts cmr ON cmr.conversation_id=cm.conversation_id AND cmr.user_id=cm.user_id WHERE cm.conversation_id=${conversations.id} AND cm.user_id<>${userId} AND cm.left_at IS NULL LIMIT 1),0) ELSE 0 END`,
    peerReadSequence:sql<number>`CASE WHEN ${conversations.type}='direct' THEN COALESCE((SELECT cmr.read_sequence FROM conversation_members cm LEFT JOIN conversation_member_receipts cmr ON cmr.conversation_id=cm.conversation_id AND cmr.user_id=cm.user_id WHERE cm.conversation_id=${conversations.id} AND cm.user_id<>${userId} AND cm.left_at IS NULL LIMIT 1),0) ELSE 0 END`
  }).from(conversationMembers).innerJoin(conversations,eq(conversationMembers.conversationId,conversations.id)).where(and(eq(conversationMembers.userId,userId),isNull(conversationMembers.leftAt),isNull(conversations.archivedAt))).orderBy(desc(conversations.updatedAt));}
  async updateTitle(id:string,title:string){const [row]=await db.update(conversations).set({title,updatedAt:new Date()}).where(eq(conversations.id,id)).returning();return row;}

  async addMember(id:string,actorId:string,newUserId:string){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);const actor=await tx.query.conversationMembers.findFirst({where:activeMembership(id,actorId)});const c=await tx.query.conversations.findFirst({where:eq(conversations.id,id)});if(!actor||!c)return 'not-found' as const;if(c.type!=='group')return 'direct' as const;if(!['owner','admin'].includes(actor.role))return 'forbidden' as const;const existing=await tx.query.conversationMembers.findFirst({where:activeMembership(id,newUserId)});if(existing)return 'ok' as const;await tx.insert(conversationMembers).values({id:randomUUID(),conversationId:id,userId:newUserId,role:'member',joinedSequence:c.nextMessageSequence});return 'ok' as const;});}
  async updateMemberRole(id:string,actorId:string,targetId:string,role:'admin'|'member'){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);const actor=await tx.query.conversationMembers.findFirst({where:activeMembership(id,actorId)});const target=await tx.query.conversationMembers.findFirst({where:activeMembership(id,targetId)});const c=await tx.query.conversations.findFirst({where:eq(conversations.id,id)});if(!actor||!c)return 'not-found' as const;if(c.type!=='group')return 'direct' as const;if(actor.role!=='owner')return 'forbidden' as const;if(!target)return 'member-not-found' as const;if(target.role==='owner')return 'owner' as const;await tx.update(conversationMembers).set({role}).where(eq(conversationMembers.id,target.id));return 'ok' as const;});}
  async removeMember(id:string,actorId:string,targetId:string){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);const actor=await tx.query.conversationMembers.findFirst({where:activeMembership(id,actorId)});const target=await tx.query.conversationMembers.findFirst({where:activeMembership(id,targetId)});const c=await tx.query.conversations.findFirst({where:eq(conversations.id,id)});if(!actor||!c)return 'not-found' as const;if(c.type!=='group')return 'direct' as const;if(!target)return 'ok' as const;if(actorId===targetId)return 'self' as const;if(actor.role!=='owner'&&!(actor.role==='admin'&&target.role==='member'))return 'forbidden' as const;if(target.role==='owner')return 'owner' as const;await tx.update(conversationMembers).set({leftAt:new Date()}).where(eq(conversationMembers.id,target.id));return 'ok' as const;});}
  async leaveConversation(id:string,userId:string){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);const member=await tx.query.conversationMembers.findFirst({where:activeMembership(id,userId)});const c=await tx.query.conversations.findFirst({where:eq(conversations.id,id)});if(!member||!c)return 'not-found' as const;if(c.type==='direct')return 'direct' as const;if(member.role!=='owner'){await tx.update(conversationMembers).set({leftAt:new Date()}).where(eq(conversationMembers.id,member.id));return 'ok' as const;}
      const [next]=await tx.select().from(conversationMembers).where(and(eq(conversationMembers.conversationId,id),isNull(conversationMembers.leftAt),sql`${conversationMembers.userId} <> ${userId}`)).orderBy(sql`CASE WHEN ${conversationMembers.role}='admin' THEN 0 ELSE 1 END`,asc(conversationMembers.joinedAt),asc(conversationMembers.userId)).limit(1);
      if(next)await tx.update(conversationMembers).set({role:'owner'}).where(eq(conversationMembers.id,next.id));
      await tx.update(conversationMembers).set({leftAt:new Date()}).where(eq(conversationMembers.id,member.id));
      if(!next)await tx.update(conversations).set({archivedAt:new Date()}).where(eq(conversations.id,id));return 'ok' as const;});}


  async updateReceipt(id:string,userId:string,deliveredSequence:number,readSequence:number){const membership=await this.getMembership(id,userId);if(!membership)return null;const maxSequence=Math.max(0,(await db.query.conversations.findFirst({where:eq(conversations.id,id)}))!.nextMessageSequence-1);const delivered=Math.min(deliveredSequence,maxSequence),read=Math.min(readSequence,delivered);const [row]=await db.insert(conversationMemberReceipts).values({conversationId:id,userId,deliveredSequence:delivered,readSequence:read}).onConflictDoUpdate({target:[conversationMemberReceipts.conversationId,conversationMemberReceipts.userId],set:{deliveredSequence:sql`GREATEST(${conversationMemberReceipts.deliveredSequence}, ${delivered})`,readSequence:sql`GREATEST(${conversationMemberReceipts.readSequence}, ${read})`,updatedAt:new Date()}}).returning();return row;}
  async touchPresence(userId:string){const [row]=await db.insert(userPresence).values({userId,lastSeenAt:new Date()}).onConflictDoUpdate({target:userPresence.userId,set:{lastSeenAt:new Date()}}).returning();return row;}
  async listConversationPeerIds(userId:string){const mine=db.select({conversationId:conversationMembers.conversationId}).from(conversationMembers).where(and(eq(conversationMembers.userId,userId),isNull(conversationMembers.leftAt)));return db.selectDistinct({userId:conversationMembers.userId}).from(conversationMembers).where(and(inArray(conversationMembers.conversationId,mine),isNull(conversationMembers.leftAt),sql`${conversationMembers.userId} <> ${userId}`));}

  async listMessages(id:string,userId:string,before:number|undefined,after:number|undefined,limit:number){const membership=await this.getMembership(id,userId);if(!membership)return null;const lower=membership.joinedSequence;const cursor=after!==undefined?gt(messages.sequence,after):before!==undefined?lt(messages.sequence,before):undefined;const where=and(eq(messages.conversationId,id),sql`${messages.sequence} >= ${lower}`,sql`NOT EXISTS (SELECT 1 FROM message_user_deletions mud WHERE mud.message_id=${messages.id} AND mud.user_id=${userId})`,cursor);return after!==undefined?db.select().from(messages).where(where).orderBy(asc(messages.sequence)).limit(limit):db.select().from(messages).where(where).orderBy(desc(messages.sequence)).limit(limit);}
  async sendMessage(id:string,senderId:string,clientMessageId:string,body:string,mediaAssetIds:string[]=[]){return db.transaction(async tx=>{const locked=await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);if(!locked.rowCount)return null;const membership=await tx.query.conversationMembers.findFirst({where:activeMembership(id,senderId)});if(!membership)return {forbidden:true as const};const duplicate=await tx.query.messages.findFirst({where:and(eq(messages.conversationId,id),eq(messages.senderId,senderId),eq(messages.clientMessageId,clientMessageId))});if(duplicate)return {message:duplicate,created:false};const [c]=await tx.select().from(conversations).where(eq(conversations.id,id)).limit(1);if(mediaAssetIds.length){const owned=await tx.select({id:mediaAssets.id}).from(mediaAssets).where(and(inArray(mediaAssets.id,mediaAssetIds),eq(mediaAssets.ownerUserId,senderId),eq(mediaAssets.status,'ready')));if(owned.length!==mediaAssetIds.length)return {invalidAttachments:true as const};}const [message]=await tx.insert(messages).values({id:randomUUID(),conversationId:id,senderId,clientMessageId,sequence:c!.nextMessageSequence,body}).returning();if(mediaAssetIds.length){await tx.insert(messageAttachments).values(mediaAssetIds.map((mediaAssetId,position)=>({id:randomUUID(),messageId:message!.id,mediaAssetId,position})));await tx.update(mediaAssets).set({status:'attached'}).where(inArray(mediaAssets.id,mediaAssetIds));}await tx.update(conversations).set({nextMessageSequence:c!.nextMessageSequence+1,updatedAt:new Date()}).where(eq(conversations.id,id));return {message:message!,created:true};});}
  async listAttachments(messageIds:string[]){if(!messageIds.length)return [];return db.select({id:messageAttachments.id,messageId:messageAttachments.messageId,mediaAssetId:mediaAssets.id,mimeType:mediaAssets.mimeType,sizeBytes:mediaAssets.sizeBytes,originalFilename:mediaAssets.originalFilename,position:messageAttachments.position}).from(messageAttachments).innerJoin(mediaAssets,eq(mediaAssets.id,messageAttachments.mediaAssetId)).where(inArray(messageAttachments.messageId,messageIds)).orderBy(asc(messageAttachments.position));}
  async editMessage(id:string,userId:string,messageId:string,body:string){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);if(!(await tx.query.conversationMembers.findFirst({where:activeMembership(id,userId)})))return {kind:'not-found' as const};const [row]=await tx.update(messages).set({body,editedAt:new Date()}).where(and(eq(messages.id,messageId),eq(messages.conversationId,id),eq(messages.senderId,userId),isNull(messages.deletedAt))).returning();if(row)return {kind:'ok' as const,message:row};const existing=await tx.query.messages.findFirst({where:and(eq(messages.id,messageId),eq(messages.conversationId,id))});if(!existing)return {kind:'message-not-found' as const};if(existing.senderId!==userId)return {kind:'forbidden' as const};return {kind:'deleted' as const};});}
  async deleteMessageForEveryone(id:string,userId:string,messageId:string){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);if(!(await tx.query.conversationMembers.findFirst({where:activeMembership(id,userId)})))return {kind:'not-found' as const};const existing=await tx.query.messages.findFirst({where:and(eq(messages.id,messageId),eq(messages.conversationId,id))});if(!existing)return {kind:'message-not-found' as const};if(existing.senderId!==userId)return {kind:'forbidden' as const};if(existing.deletedAt)return {kind:'ok' as const,message:existing};const [row]=await tx.update(messages).set({body:'',deletedAt:new Date(),editedAt:null}).where(and(eq(messages.id,messageId),isNull(messages.deletedAt))).returning();return {kind:'ok' as const,message:row!};});}
  async deleteMessageForUser(id:string,userId:string,messageId:string){const membership=await this.getMembership(id,userId);if(!membership)return {kind:'not-found' as const};const message=await db.query.messages.findFirst({where:and(eq(messages.id,messageId),eq(messages.conversationId,id),sql`${messages.sequence} >= ${membership.joinedSequence}`)});if(!message)return {kind:'message-not-found' as const};await db.insert(messageUserDeletions).values({messageId,userId}).onConflictDoNothing({target:[messageUserDeletions.messageId,messageUserDeletions.userId]});return {kind:'ok' as const,message};}
}
export const chatRepository=new ChatRepository();
