import { randomUUID } from 'node:crypto';
import { and, asc, desc, eq, gt, inArray, isNull, lt, sql } from 'drizzle-orm';
import { db } from '@/db/client';
import { conversationMembers, conversations, messages, users } from '@/db/schema';

type MemberRole = 'owner' | 'admin' | 'member';
const activeMembership = (conversationId:string,userId:string) => and(eq(conversationMembers.conversationId,conversationId),eq(conversationMembers.userId,userId),isNull(conversationMembers.leftAt));

class ChatRepository {
  async usersExist(userIds:string[]){if(!userIds.length)return true;const rows=await db.select({id:users.id}).from(users).where(inArray(users.id,userIds));return rows.length===new Set(userIds).size;}
  async createConversation(creatorId:string,participantUserIds:string[],type:'direct'|'group',title?:string){
    const memberIds=[...new Set([creatorId,...participantUserIds])]; const directKey=type==='direct'?[...memberIds].sort().join(':'):null;
    return db.transaction(async tx=>{
      if(directKey){const existing=await tx.query.conversations.findFirst({where:eq(conversations.directKey,directKey)});if(existing)return existing;}
      const insert=tx.insert(conversations).values({id:randomUUID(),type,directKey,title:type==='group'?title:null});
      const [created]=directKey?await insert.onConflictDoNothing({target:conversations.directKey}).returning():await insert.returning();
      if(!created&&directKey){const existing=await tx.query.conversations.findFirst({where:eq(conversations.directKey,directKey)});if(existing)return existing;throw new Error('Direct conversation conflict did not resolve');}
      const conversation=created!;
      await tx.insert(conversationMembers).values(memberIds.map(userId=>({id:randomUUID(),conversationId:conversation.id,userId,role:type==='group'&&userId===creatorId?'owner' as const:'member' as const,joinedSequence:1})));
      return conversation;
    });
  }
  getConversation(id:string){return db.query.conversations.findFirst({where:eq(conversations.id,id)});}
  getMessage(id:string,messageId:string){return db.query.messages.findFirst({where:and(eq(messages.id,messageId),eq(messages.conversationId,id))});}
  getMembership(id:string,userId:string){return db.query.conversationMembers.findFirst({where:activeMembership(id,userId)});}
  listMembers(id:string){return db.select({userId:users.id,displayName:users.displayName,avatarUrl:users.avatarUrl,role:conversationMembers.role,joinedAt:conversationMembers.joinedAt}).from(conversationMembers).innerJoin(users,eq(users.id,conversationMembers.userId)).where(and(eq(conversationMembers.conversationId,id),isNull(conversationMembers.leftAt)));}
  listMessageRecipientIds(id:string,sequence:number){return db.select({userId:conversationMembers.userId}).from(conversationMembers).where(and(eq(conversationMembers.conversationId,id),isNull(conversationMembers.leftAt),sql`${conversationMembers.joinedSequence} <= ${sequence}`));}
  listConversations(userId:string){return db.select({
    id:conversations.id,type:conversations.type,title:conversations.title,createdAt:conversations.createdAt,updatedAt:conversations.updatedAt,archivedAt:conversations.archivedAt,
    displayTitle:sql<string>`CASE WHEN ${conversations.type} = 'direct' THEN COALESCE((SELECT u.display_name FROM conversation_members cm JOIN users u ON u.id = cm.user_id WHERE cm.conversation_id = ${conversations.id} AND cm.user_id <> ${userId} AND cm.left_at IS NULL LIMIT 1), 'Conversation') ELSE COALESCE(${conversations.title}, 'Group conversation') END`,
    avatarUrl:sql<string|null>`CASE WHEN ${conversations.type} = 'direct' THEN (SELECT u.avatar_url FROM conversation_members cm JOIN users u ON u.id = cm.user_id WHERE cm.conversation_id = ${conversations.id} AND cm.user_id <> ${userId} AND cm.left_at IS NULL LIMIT 1) ELSE NULL END`,
    lastMessage:sql<string|null>`(SELECT CASE WHEN m.deleted_at IS NULL THEN m.body ELSE '' END FROM messages m WHERE m.conversation_id = ${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} ORDER BY m.sequence DESC LIMIT 1)`,
    lastMessageAt:sql<Date|null>`(SELECT m.created_at FROM messages m WHERE m.conversation_id = ${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} ORDER BY m.sequence DESC LIMIT 1)`,
    lastMessageSenderId:sql<string|null>`(SELECT m.sender_id FROM messages m WHERE m.conversation_id = ${conversations.id} AND m.sequence >= ${conversationMembers.joinedSequence} ORDER BY m.sequence DESC LIMIT 1)`
  }).from(conversationMembers).innerJoin(conversations,eq(conversationMembers.conversationId,conversations.id)).where(and(eq(conversationMembers.userId,userId),isNull(conversationMembers.leftAt),isNull(conversations.archivedAt))).orderBy(desc(conversations.updatedAt));}
  async updateTitle(id:string,title:string){const [row]=await db.update(conversations).set({title,updatedAt:new Date()}).where(eq(conversations.id,id)).returning();return row;}

  async addMember(id:string,actorId:string,newUserId:string){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);const actor=await tx.query.conversationMembers.findFirst({where:activeMembership(id,actorId)});const c=await tx.query.conversations.findFirst({where:eq(conversations.id,id)});if(!actor||!c)return 'not-found' as const;if(c.type!=='group')return 'direct' as const;if(!['owner','admin'].includes(actor.role))return 'forbidden' as const;const existing=await tx.query.conversationMembers.findFirst({where:activeMembership(id,newUserId)});if(existing)return 'ok' as const;await tx.insert(conversationMembers).values({id:randomUUID(),conversationId:id,userId:newUserId,role:'member',joinedSequence:c.nextMessageSequence});return 'ok' as const;});}
  async updateMemberRole(id:string,actorId:string,targetId:string,role:'admin'|'member'){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);const actor=await tx.query.conversationMembers.findFirst({where:activeMembership(id,actorId)});const target=await tx.query.conversationMembers.findFirst({where:activeMembership(id,targetId)});const c=await tx.query.conversations.findFirst({where:eq(conversations.id,id)});if(!actor||!c)return 'not-found' as const;if(c.type!=='group')return 'direct' as const;if(actor.role!=='owner')return 'forbidden' as const;if(!target)return 'member-not-found' as const;if(target.role==='owner')return 'owner' as const;await tx.update(conversationMembers).set({role}).where(eq(conversationMembers.id,target.id));return 'ok' as const;});}
  async removeMember(id:string,actorId:string,targetId:string){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);const actor=await tx.query.conversationMembers.findFirst({where:activeMembership(id,actorId)});const target=await tx.query.conversationMembers.findFirst({where:activeMembership(id,targetId)});const c=await tx.query.conversations.findFirst({where:eq(conversations.id,id)});if(!actor||!c)return 'not-found' as const;if(c.type!=='group')return 'direct' as const;if(!target)return 'ok' as const;if(actorId===targetId)return 'self' as const;if(actor.role!=='owner'&&!(actor.role==='admin'&&target.role==='member'))return 'forbidden' as const;if(target.role==='owner')return 'owner' as const;await tx.update(conversationMembers).set({leftAt:new Date()}).where(eq(conversationMembers.id,target.id));return 'ok' as const;});}
  async leaveConversation(id:string,userId:string){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);const member=await tx.query.conversationMembers.findFirst({where:activeMembership(id,userId)});const c=await tx.query.conversations.findFirst({where:eq(conversations.id,id)});if(!member||!c)return 'not-found' as const;if(c.type==='direct')return 'direct' as const;if(member.role!=='owner'){await tx.update(conversationMembers).set({leftAt:new Date()}).where(eq(conversationMembers.id,member.id));return 'ok' as const;}
      const [next]=await tx.select().from(conversationMembers).where(and(eq(conversationMembers.conversationId,id),isNull(conversationMembers.leftAt),sql`${conversationMembers.userId} <> ${userId}`)).orderBy(sql`CASE WHEN ${conversationMembers.role}='admin' THEN 0 ELSE 1 END`,asc(conversationMembers.joinedAt),asc(conversationMembers.userId)).limit(1);
      if(next)await tx.update(conversationMembers).set({role:'owner'}).where(eq(conversationMembers.id,next.id));
      await tx.update(conversationMembers).set({leftAt:new Date()}).where(eq(conversationMembers.id,member.id));
      if(!next)await tx.update(conversations).set({archivedAt:new Date()}).where(eq(conversations.id,id));return 'ok' as const;});}

  async listMessages(id:string,userId:string,before:number|undefined,after:number|undefined,limit:number){const membership=await this.getMembership(id,userId);if(!membership)return null;const lower=membership.joinedSequence;const cursor=after!==undefined?gt(messages.sequence,after):before!==undefined?lt(messages.sequence,before):undefined;const where=and(eq(messages.conversationId,id),sql`${messages.sequence} >= ${lower}`,cursor);return after!==undefined?db.select().from(messages).where(where).orderBy(asc(messages.sequence)).limit(limit):db.select().from(messages).where(where).orderBy(desc(messages.sequence)).limit(limit);}
  async sendMessage(id:string,senderId:string,clientMessageId:string,body:string){return db.transaction(async tx=>{const locked=await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);if(!locked.rowCount)return null;const membership=await tx.query.conversationMembers.findFirst({where:activeMembership(id,senderId)});if(!membership)return {forbidden:true as const};const duplicate=await tx.query.messages.findFirst({where:and(eq(messages.conversationId,id),eq(messages.senderId,senderId),eq(messages.clientMessageId,clientMessageId))});if(duplicate)return {message:duplicate,created:false};const [c]=await tx.select().from(conversations).where(eq(conversations.id,id)).limit(1);const [message]=await tx.insert(messages).values({id:randomUUID(),conversationId:id,senderId,clientMessageId,sequence:c!.nextMessageSequence,body}).returning();await tx.update(conversations).set({nextMessageSequence:c!.nextMessageSequence+1,updatedAt:new Date()}).where(eq(conversations.id,id));return {message:message!,created:true};});}
  async editMessage(id:string,userId:string,messageId:string,body:string){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);if(!(await tx.query.conversationMembers.findFirst({where:activeMembership(id,userId)})))return {kind:'not-found' as const};const [row]=await tx.update(messages).set({body,editedAt:new Date()}).where(and(eq(messages.id,messageId),eq(messages.conversationId,id),eq(messages.senderId,userId),isNull(messages.deletedAt))).returning();if(row)return {kind:'ok' as const,message:row};const existing=await tx.query.messages.findFirst({where:and(eq(messages.id,messageId),eq(messages.conversationId,id))});if(!existing)return {kind:'message-not-found' as const};if(existing.senderId!==userId)return {kind:'forbidden' as const};return {kind:'deleted' as const};});}
  async deleteMessage(id:string,userId:string,messageId:string){return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM conversations WHERE id=${id} AND archived_at IS NULL FOR UPDATE`);if(!(await tx.query.conversationMembers.findFirst({where:activeMembership(id,userId)})))return {kind:'not-found' as const};const existing=await tx.query.messages.findFirst({where:and(eq(messages.id,messageId),eq(messages.conversationId,id))});if(!existing)return {kind:'message-not-found' as const};if(existing.senderId!==userId)return {kind:'forbidden' as const};if(existing.deletedAt)return {kind:'ok' as const,message:existing};const [row]=await tx.update(messages).set({body:'',deletedAt:new Date(),editedAt:null}).where(and(eq(messages.id,messageId),isNull(messages.deletedAt))).returning();return {kind:'ok' as const,message:row!};});}
}
export const chatRepository=new ChatRepository();
