import jwt from 'jsonwebtoken';
import type { Role } from '@vibeline/contracts';
import { AppError } from '@/common/errors/app-error';
import { env } from '@/config/env';
type JwtUserPayload={id:string;email:string;role:Role};
type OAuthProvider='google';
type OAuthStatePayload={provider:OAuthProvider;type:'oauth_state'};
export const signAccessToken=(user:JwtUserPayload)=>jwt.sign({sub:user.id,email:user.email,role:user.role,type:'access'},env.JWT_SECRET,{expiresIn:env.JWT_EXPIRES_IN as jwt.SignOptions['expiresIn']});
export const signOAuthState=(provider:OAuthProvider)=>jwt.sign({provider,type:'oauth_state'} satisfies OAuthStatePayload,env.OAUTH_STATE_SECRET,{expiresIn:'10m'});
export const verifyOAuthState=(state:string,provider:OAuthProvider)=>{try{const p=jwt.verify(state,env.OAUTH_STATE_SECRET) as Partial<OAuthStatePayload>;if(p.type!=='oauth_state'||p.provider!==provider)throw new Error();}catch{throw new AppError(401,'INVALID_OAUTH_STATE','OAuth state is invalid or expired');}};
