import { z } from 'zod';

export const apiErrorCodes = [
  'VALIDATION_ERROR','INVALID_CREDENTIALS','INVALID_ACCESS_TOKEN','INVALID_REFRESH_TOKEN','REFRESH_TOKEN_REUSED',
  'INVALID_TOKEN','TOKEN_EXPIRED','EMAIL_IN_USE','EMAIL_NOT_VERIFIED','VERIFICATION_FAILED','ALREADY_VERIFIED',
  'PASSWORD_ALREADY_CONFIGURED','INVALID_OAUTH_STATE','OAUTH_EMAIL_UNVERIFIED','ACCOUNT_LINK_REQUIRED','RATE_LIMITED',
  'FORBIDDEN','CONVERSATION_NOT_FOUND','MESSAGE_NOT_FOUND','MEMBER_NOT_FOUND','USER_NOT_FOUND',
  'INVALID_PARTICIPANTS','INVALID_DIRECT_PARTICIPANTS','DIRECT_CONVERSATION_IMMUTABLE','DIRECT_MEMBERS_IMMUTABLE',
  'DIRECT_CONVERSATION_LEAVE_UNSUPPORTED','OWNER_ROLE_IMMUTABLE','OWNER_CANNOT_BE_REMOVED','MESSAGE_DELETED',
  'INTERNAL_SERVER_ERROR'
] as const;
export const apiErrorCodeSchema = z.enum(apiErrorCodes);
export type ApiErrorCode = z.infer<typeof apiErrorCodeSchema>;
export const apiErrorResponseSchema = z.object({ code: z.string().min(1), message: z.string().min(1) });
export type ApiErrorResponse = z.infer<typeof apiErrorResponseSchema>;
