'use client';
import { useMemo, useState } from 'react';
import type { UserSearchResult } from '@vibeline/contracts';
import { Check, Clock3, X } from 'lucide-react';
import { ChatAvatar } from './chat-avatar';

const ONLINE_MS=45_000;
const lastActive=(value?:string)=>{if(!value)return 'Not recently active';const ms=Date.now()-new Date(value).getTime();if(ms<ONLINE_MS)return 'Active now';const minutes=Math.max(1,Math.floor(ms/60_000));if(minutes<60)return `${minutes} min.`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours} hr.`;const days=Math.floor(hours/24);return days<7?`${days} d.`:new Date(value).toLocaleDateString([],{month:'short',day:'numeric'});};

type Props={people:UserSearchResult[];query:string;onQuery:(v:string)=>void;onStart:(u:UserSearchResult)=>void;onRequestConnection:(userId:string)=>Promise<void>;onRespondConnection?:(id:string,accept:boolean)=>Promise<void>;onAddContact:()=>void};

export function PeoplePanel({people,query,onQuery,onStart,onRequestConnection,onRespondConnection,onAddContact}:Props){
 const [busy,setBusy]=useState<string>();
 const {active,recent,other}=useMemo(()=>{const now=Date.now();const active:UserSearchResult[]=[],recent:UserSearchResult[]=[],other:UserSearchResult[]=[];for(const user of people){if(user.lastSeenAt&&now-new Date(user.lastSeenAt).getTime()<ONLINE_MS)active.push(user);else if(user.lastSeenAt)recent.push(user);else other.push(user);}return{active,recent,other};},[people]);
 const connect=async(user:UserSearchResult)=>{if(user.connectionStatus!=='none')return;setBusy(user.id);try{await onRequestConnection(user.id);}finally{setBusy(undefined);}};
 const respond=async(user:UserSearchResult,accept:boolean)=>{if(!onRespondConnection||!user.connectionRequestId)return;setBusy(user.id);try{await onRespondConnection(user.connectionRequestId,accept);}finally{setBusy(undefined);}};
 const action=(user:UserSearchResult)=>{if(user.connectionStatus==='outgoing')return <span className="ml-2 inline-flex h-8 shrink-0 items-center gap-1.5 rounded-full bg-black/[.05] px-3 text-xs font-semibold text-black/55"><Clock3 size={14}/>Sent</span>;if(user.connectionStatus==='connected')return <span className="ml-2 inline-flex h-8 shrink-0 items-center gap-1.5 rounded-full bg-[#E9F7E5] px-3 text-xs font-semibold text-[#287A35]"><Check size={14}/>Connected</span>;if(user.connectionStatus==='incoming'&&user.connectionRequestId&&onRespondConnection)return <span className="ml-2 flex shrink-0 gap-1.5"><button onClick={()=>void respond(user,false)} disabled={busy===user.id} title="Decline request" className="grid h-8 w-8 place-items-center rounded-full bg-black/[.05] disabled:opacity-45"><X size={15}/></button><button onClick={()=>void respond(user,true)} disabled={busy===user.id} title="Accept request" className="grid h-8 w-8 place-items-center rounded-full bg-[#E9F7E5] text-[#287A35] disabled:opacity-45"><Check size={16}/></button></span>;return <button onClick={()=>void connect(user)} disabled={busy===user.id} title="Add contact" className="ml-2 grid h-8 w-8 shrink-0 place-items-center rounded-full bg-black/[.04] disabled:opacity-45"><img src="/assets/chat/add-contact.svg" alt="" width={18} height={16}/></button>;};
 const row=(user:UserSearchResult)=>{const online=!!user.lastSeenAt&&Date.now()-new Date(user.lastSeenAt).getTime()<ONLINE_MS;return <div key={user.id} className="group flex h-[60px] items-center px-4 transition-colors hover:bg-black/[.025]"><div className="relative"><ChatAvatar name={user.displayName} src={user.avatarUrl} online={online}/>{!online&&user.lastSeenAt&&<span className="absolute -bottom-1 -left-0.5 min-w-[38px] rounded-[5px] border-[3px] border-white bg-[#C7F0BB] px-1 text-center text-[8px] font-medium leading-[14px] tracking-[.3px] text-black">{lastActive(user.lastSeenAt)}</span>}</div><button onClick={()=>onStart(user)} className="min-w-0 flex-1 px-3 text-left"><span className="block truncate text-[17px] font-medium leading-[22px] tracking-[-.2px] text-black">{user.displayName}</span>{query&&<span className="block truncate text-[12px] text-black/45">{user.email}</span>}</button><button onClick={()=>onStart(user)} title={`Wave to ${user.displayName}`} className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-black/[.07] transition-transform duration-200 hover:scale-110 active:scale-90"><img src="/assets/chat/wave.svg" alt="" width={16} height={17} className="origin-bottom transition-transform duration-200 group-hover:rotate-12"/></button>{action(user)}</div>};
 return <div className="flex min-h-0 flex-1 flex-col"><div className="px-4 pb-2"><label className="flex h-9 items-center gap-2 rounded-[10px] bg-black/[.05] px-2"><img src="/assets/chat/search.svg" alt="" width={16} height={16}/><input autoFocus={false} value={query} onChange={e=>onQuery(e.target.value)} placeholder="Search" className="min-w-0 flex-1 bg-transparent text-[17px] leading-[22px] tracking-[-.41px] text-black outline-none placeholder:text-[#8E8E93]"/></label></div><button onClick={onAddContact} className="flex h-[72px] shrink-0 items-center px-4 text-left transition-colors hover:bg-black/[.025]"><span className="grid h-10 w-10 place-items-center rounded-full bg-black/[.04]"><img src="/assets/chat/plus.svg" alt="" width={15} height={15}/></span><span className="ml-3"><strong className="block text-[17px] font-medium leading-[22px] tracking-[-.2px]">Add people</strong><span className="block text-[13px] leading-[18px] tracking-[-.08px] text-black/50">Find someone by name or email</span></span></button><div className="min-h-0 flex-1 overflow-y-auto pb-24 md:pb-4">{active.map(row)}{recent.length>0&&<><h2 className="px-4 pb-1 pt-5 text-[13px] font-medium uppercase tracking-[.2px] text-black/30">Recently active</h2>{recent.map(row)}</>}{other.length>0&&<><h2 className="px-4 pb-1 pt-5 text-[13px] font-medium uppercase tracking-[.2px] text-black/30">People</h2>{other.map(row)}</>}{!people.length&&<p className="px-4 py-10 text-center text-sm text-black/45">No people found.</p>}</div></div>;
}