'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import type { MouseEvent } from 'react';
import { Mic,Pause,Play,Send,Square,Trash2 } from 'lucide-react';
import { cn } from '@vibeline/utils';
import type { MessageAttachment } from '@vibeline/contracts';

const format=(seconds:number)=>{const safe=Number.isFinite(seconds)&&seconds>0?seconds:0;return `${Math.floor(safe/60)}:${String(Math.floor(safe%60)).padStart(2,'0')}`};
const fallbackBars=Array.from({length:42},(_,i)=>0.22+(((i*17)%13)/18));

async function waveform(blob:Blob,count=42){
 try{const context=new AudioContext();const buffer=await context.decodeAudioData(await blob.arrayBuffer());const data=buffer.getChannelData(0);const size=Math.max(1,Math.floor(data.length/count));const bars=Array.from({length:count},(_,index)=>{let peak=0;const start=index*size,end=Math.min(data.length,start+size);for(let i=start;i<end;i++)peak=Math.max(peak,Math.abs(data[i]??0));return peak});const max=Math.max(...bars,.01);void context.close();return bars.map(value=>Math.max(.14,value/max));}catch{return fallbackBars}
}

function WaveBars({bars,progress,own=false,live=false,level=0}:{bars:number[];progress:number;own?:boolean;live?:boolean;level?:number}){
 return <div className="flex h-9 min-w-0 flex-1 items-center gap-[2px] overflow-hidden" aria-hidden="true">{bars.map((value,index)=>{const active=index/Math.max(1,bars.length-1)<=progress;const liveHeight=live?Math.max(.16,Math.min(1,value*(.45+level*1.5))):value;return <span key={index} className={cn('w-[3px] shrink-0 rounded-full transition-[height,background-color] duration-75',active?(own?'bg-white':'bg-[#0584FE]'):(own?'bg-white/35':'bg-black/20'))} style={{height:`${Math.round(5+liveHeight*24)}px`}}/>})}</div>
}

function VoicePlayer({src,own=false,compact=false}:{src:string;own?:boolean;compact?:boolean}){
 const audio=useRef<HTMLAudioElement|null>(null);const [playing,setPlaying]=useState(false);const [duration,setDuration]=useState(0);const [current,setCurrent]=useState(0);const [bars,setBars]=useState<number[]>(fallbackBars);
 useEffect(()=>{if(!src)return;let active=true;fetch(src).then(r=>r.blob()).then(blob=>waveform(blob)).then(values=>{if(active)setBars(values)}).catch(()=>undefined);return()=>{active=false}},[src]);
 const syncDuration=(el:HTMLAudioElement)=>{const value=el.duration;if(Number.isFinite(value)&&value>0)setDuration(value)};
 const toggle=()=>{const el=audio.current;if(!el||!src)return;if(el.paused){document.querySelectorAll('audio[data-voice-message]').forEach(node=>{if(node!==el)(node as HTMLAudioElement).pause()});void el.play()}else el.pause()};
 const seek=(event:MouseEvent<HTMLDivElement>)=>{const el=audio.current;if(!el||!duration)return;const rect=event.currentTarget.getBoundingClientRect();const next=Math.max(0,Math.min(duration,((event.clientX-rect.left)/rect.width)*duration));el.currentTime=next;setCurrent(next)};
 const progress=duration?Math.min(1,current/duration):0;
 return <div className={cn('flex min-w-0 items-center gap-2.5',compact?'w-full':'min-w-[245px] max-w-[330px]')}><button type="button" onClick={toggle} disabled={!src} aria-label={playing?'Pause voice message':'Play voice message'} className={cn('grid h-10 w-10 shrink-0 place-items-center rounded-full transition-transform active:scale-95 disabled:opacity-50',own?'bg-white/20 text-white':'bg-[#0584FE] text-white')}>{playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor" className="ml-0.5"/>}</button><div className="flex min-h-12 min-w-0 flex-1 flex-col justify-center"><div onClick={seek} className="flex h-9 cursor-pointer items-center"><WaveBars bars={bars} progress={progress} own={own}/></div><div className={cn('-mt-0.5 flex items-center justify-between text-[11px] tabular-nums',own?'text-white/75':'text-black/45')}><span>{playing||current>0?format(current):format(duration)}</span>{playing&&<span className="text-[10px]">1×</span>}</div></div><audio ref={audio} data-voice-message src={src} preload="metadata" onLoadedMetadata={e=>syncDuration(e.currentTarget)} onDurationChange={e=>syncDuration(e.currentTarget)} onTimeUpdate={e=>{setCurrent(e.currentTarget.currentTime);syncDuration(e.currentTarget)}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>{setPlaying(false);setCurrent(0)}}/></div>
}

export function VoiceMessage({attachment,onLoad,own}:{attachment:MessageAttachment;onLoad:(url:string)=>Promise<Blob>;own:boolean}){
 const [src,setSrc]=useState('');
 useEffect(()=>{let active=true,url='';void onLoad(attachment.url).then(async blob=>{if(active){const audioBlob=blob.type.startsWith('audio/')?blob:new Blob([await blob.arrayBuffer()],{type:/\.(?:ogg|oga|opus)$/i.test(attachment.originalFilename??'')?'audio/ogg':/\.(?:m4a|mp4)$/i.test(attachment.originalFilename??'')?'audio/mp4':'audio/webm'});url=URL.createObjectURL(audioBlob);setSrc(url)}}).catch(()=>undefined);return()=>{active=false;if(url)URL.revokeObjectURL(url)}},[attachment.url,onLoad]);
 return <VoicePlayer src={src} own={own}/>;
}

type RecorderProps={disabled:boolean;onCancel:()=>void;onSend:(file:File)=>Promise<void>};
export function VoiceRecorder({disabled,onCancel,onSend}:RecorderProps){
 const [state,setState]=useState<'starting'|'recording'|'paused'|'preview'|'error'>('starting');const [seconds,setSeconds]=useState(0);const [level,setLevel]=useState(0);const [error,setError]=useState('');const [preview,setPreview]=useState('');const [samples,setSamples]=useState<number[]>(Array(42).fill(.18));
 const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const chunks=useRef<Blob[]>([]);const file=useRef<File|null>(null);const timer=useRef<number|null>(null);const frame=useRef<number|null>(null);const previewRef=useRef('');
 const setPreviewUrl=useCallback((url:string)=>{if(previewRef.current)URL.revokeObjectURL(previewRef.current);previewRef.current=url;setPreview(url)},[]);
 useEffect(()=>{let mounted=true;let context:AudioContext|null=null;const start=async()=>{try{const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(!mounted){media.getTracks().forEach(t=>t.stop());return}stream.current=media;const candidates=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4'];const mime=candidates.find(v=>MediaRecorder.isTypeSupported(v))||'';const r=new MediaRecorder(media,mime?{mimeType:mime}:undefined);recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{const type=r.mimeType||chunks.current[0]?.type||'audio/webm';const blob=new Blob(chunks.current,{type});const ext=type.includes('ogg')?'ogg':type.includes('mp4')?'m4a':'webm';file.current=new File([blob],`voice-${Date.now()}.${ext}`,{type});setPreviewUrl(URL.createObjectURL(blob));setState('preview')};r.start(250);setState('recording');context=new AudioContext();const source=context.createMediaStreamSource(media),analyser=context.createAnalyser();analyser.fftSize=64;source.connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);const tick=()=>{analyser.getByteFrequencyData(data);const next=data.reduce((a,b)=>a+b,0)/(data.length*255);setLevel(next);setSamples(previous=>[...previous.slice(1),Math.max(.14,Math.min(1,next*1.8))]);frame.current=requestAnimationFrame(tick)};tick()}catch(e){setError(e instanceof DOMException&&e.name==='NotAllowedError'?'Microphone permission is blocked. Allow microphone access in your browser settings.':'Unable to access your microphone.');setState('error')}};void start();return()=>{mounted=false;if(timer.current!==null)clearInterval(timer.current);if(frame.current!==null)cancelAnimationFrame(frame.current);stream.current?.getTracks().forEach(t=>t.stop());if(context)void context.close();if(previewRef.current)URL.revokeObjectURL(previewRef.current)}},[setPreviewUrl]);
 useEffect(()=>{if(state==='recording'){timer.current=window.setInterval(()=>setSeconds(v=>v+1),1000);return()=>{if(timer.current!==null){clearInterval(timer.current);timer.current=null}}}},[state]);
 const stop=()=>{if(recorder.current&&recorder.current.state!=='inactive')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop())};
 const togglePause=()=>{const r=recorder.current;if(!r)return;if(r.state==='recording'){r.pause();setState('paused')}else if(r.state==='paused'){r.resume();setState('recording')}};
 const discard=()=>{if(recorder.current&&recorder.current.state!=='inactive'){recorder.current.onstop=null;recorder.current.stop()}stream.current?.getTracks().forEach(t=>t.stop());onCancel()};
 const send=async()=>{if(!file.current||disabled)return;await onSend(file.current);onCancel()};
 if(state==='error')return <div className="mb-2 flex items-center gap-2 rounded-2xl border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700"><span className="flex-1">{error}</span><button type="button" onClick={onCancel} className="font-semibold">Close</button></div>;
 if(state==='preview')return <div className="mb-2 flex min-h-[64px] items-center gap-3 rounded-[22px] border border-black/[.07] bg-white px-3 py-2 shadow-[0_4px_18px_rgba(0,0,0,.06)]"><button type="button" onClick={discard} aria-label="Discard recording" className="grid h-10 w-10 shrink-0 place-items-center rounded-full text-black/55 transition-colors hover:bg-black/[.05]"><Trash2 size={18}/></button><VoicePlayer src={preview} compact/><button type="button" disabled={disabled} onClick={()=>void send()} aria-label="Send voice message" className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#0584FE] text-white shadow-sm transition-transform active:scale-95 disabled:opacity-50"><Send size={19} fill="currentColor"/></button></div>;
 return <div className="mb-2 flex min-h-[62px] items-center gap-2.5 rounded-[22px] border border-black/[.07] bg-white px-3 py-2 shadow-[0_4px_18px_rgba(0,0,0,.06)]"><button type="button" onClick={discard} aria-label="Cancel recording" className="grid h-10 w-10 shrink-0 place-items-center rounded-full text-black/50 transition-colors hover:bg-black/[.05]"><Trash2 size={18}/></button><span className={cn('h-2.5 w-2.5 shrink-0 rounded-full bg-red-500',state==='recording'&&'animate-pulse')}/><span className="w-11 shrink-0 text-[13px] font-medium tabular-nums text-black/65">{format(seconds)}</span><WaveBars bars={samples} progress={1} live={state==='recording'} level={level}/><button type="button" onClick={togglePause} aria-label={state==='paused'?'Resume recording':'Pause recording'} className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-black/[.05] text-black/70 transition-transform active:scale-95">{state==='paused'?<Mic size={18}/>:<Pause size={18} fill="currentColor"/>}</button><button type="button" onClick={stop} aria-label="Finish recording" className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#0584FE] text-white transition-transform active:scale-95"><Square size={13} fill="currentColor"/></button></div>;
}
