'use client';
import { useCallback,useEffect,useState } from 'react';
import { useAuthorizedRequest } from '@/src/features/chat/hooks/use-authorized-request';
const decode=(value:string)=>{const padded=value+'='.repeat((4-value.length%4)%4);const raw=atob(padded.replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(raw,c=>c.charCodeAt(0));};
export function usePushNotifications(){
 const request=useAuthorizedRequest();const [supported,setSupported]=useState(false);const [permission,setPermission]=useState<NotificationPermission>('default');const [enabled,setEnabled]=useState(false);
 useEffect(()=>{const ok='serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window;setSupported(ok);if(ok)setPermission(Notification.permission);},[]);
 const syncSubscription=useCallback(async()=>{const config=await request<{publicKey:string|null}>('/notifications/config');if(!config.publicKey)throw new Error('Push notifications are not configured on the server');const registration=await navigator.serviceWorker.register('/push-sw.js');await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decode(config.publicKey)});const json=subscription.toJSON();if(!json.endpoint||!json.keys?.p256dh||!json.keys?.auth)throw new Error('Browser returned an incomplete push subscription');await request('/notifications/subscriptions',{method:'POST',body:{endpoint:json.endpoint,keys:{p256dh:json.keys.p256dh,auth:json.keys.auth}}});return subscription;},[request]);
 const enable=useCallback(async()=>{if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))return false;const result=Notification.permission==='granted'?'granted':await Notification.requestPermission();setPermission(result);if(result!=='granted')return false;await syncSubscription();await request('/notifications/preferences',{method:'PUT',body:{enabled:true,messagesEnabled:true,connectionsEnabled:true}});setEnabled(true);return true;},[request,syncSubscription]);
 const disable=useCallback(async()=>{if(!('serviceWorker'in navigator))return;const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.getSubscription();if(subscription){await request('/notifications/subscriptions',{method:'DELETE',body:{endpoint:subscription.endpoint}});await subscription.unsubscribe();}await request('/notifications/preferences',{method:'PUT',body:{enabled:false,messagesEnabled:true,connectionsEnabled:true}});setEnabled(false);},[request]);
 useEffect(()=>{if(!supported||permission!=='granted')return;let cancelled=false;void syncSubscription().then(()=>request('/notifications/preferences',{method:'PUT',body:{enabled:true,messagesEnabled:true,connectionsEnabled:true}})).then(()=>{if(!cancelled)setEnabled(true);}).catch(()=>{if(!cancelled)setEnabled(false);});return()=>{cancelled=true;};},[supported,permission,request,syncSubscription]);
 return {supported,permission,enabled,enable,disable};
}
